### ISSUE TITLE
Searching the wrong box

### ISSUE THREAD

**Issue by nlincke** [filiphanes/fts-elastic#11]
Hey,

its me again. First, thanks for the help the last time. I hope it is ok if i have another question. It might be that i am doing something wrong again...

I noticed that not all mails ware listed if a search for a particular keyword. I was testing this by searching for a particular mail in a sub folder... but the mail was not displayed when i was searching for the exact subject field...

I was running the search by hand directly on my elastic search system with the search string copied from the logs... the mail was not there (same behavior as on my phone)... 
It turned out that the box field of the mail was not matching the one of the search query. As soon as i deleted the box field inside the search query, the mail was shown...
And indeed the box field contains a different box string than the one in the seach query from the plugin/dovecot...

What is the box parameter used for? Can you give me some pointers?

Thanks again...

**Comment by filiphanes** [comment]
box is mailbox GUID, you check it via IMAP using this command for INBOX
`1 STATUS INBOX (X-GUID)`
guid doesn't change between mailbox renames
only virtual mailboxes does not have guid

**Comment by nlincke** [comment]
Sorry for the late reply.

I checked it and the folders do have different GUIDs.

```
1 STATUS INBOX/Rezepte (X-GUID)
* STATUS INBOX/Rezepte (X-GUID 0d432d37602e305ac15b00007dd2b51e)
1 OK Status completed (0.006 + 0.000 + 0.005 secs).
1 STATUS INBOX (X-GUID)
* STATUS INBOX (X-GUID ac410b3a2bb6ec59f62100007dd2b51e)
1 OK Status completed (0.027 + 0.000 + 0.026 secs).
```

Is my setup wierd? (Actually i am copying mails from my 'productive' system to the new one i am testing right now; The old one does not have FTS....; Everithing else is working just fine...) Or would it make sense to turn the box parameter off while the search?

**Comment by filiphanes** [comment]
yes, each mailbox have different guid, they are Globally Unique IDs
these guids are used in fts-elastic so it can search inside one mailbox an have all emails in one index and it should't be reindexed when mailbox renames

Are you trying to search in INBOX and expecting to find emails in INBOX/Rezepte?
This is not how IMAP works. They are different mailboxes only have common prefix. SEARCH command is returning UIDs only from 1 mailbox (which you SELECTed).
You need to search in sub mailboxes by SELECTing and SEARCHing each mailbox separately.
Or you can create virtual mailbox which can group many mailboxes and then search in it, then you can get original mailbox name by FETCHing X-MAILBOX.

**Comment by nlincke** [comment]
I am using the vanilla andorid mail client, I opened the folder Rezepte and could not find any mail inside this folder...
I guess the client is requesting the wrong GUID? Have you experienced anything like this? Or am I expecting the wrong things here?

**Comment by filiphanes** [comment]
Clients don't work with GUIDs, guids are only Dovecot internals. Clients are working with mailbox names (INBOX/Rezepte) and UIDs identifying email messages (1, 2, 3).
I have not used Android imap client and I have not experienced this behavior on Dovecot.


You could try to look at IMAP rawlogs https://wiki.dovecot.org/Debugging/Rawlog and see what mailbox is your client SELECTing and SEARCHing.

OR you could try search manually in IMAP using these commands:
1 SELECT INBOX/Rezepte
1 STATUS INBOX/Rezepte (X-GUID)
1 UID SEARCH SUBJECT "Best sweet cake"
and then look to fts-elastic rawlogs if x-guid matches with `box`
and if IMAP returned something, if yes if returned UID matches with first number in elastic document `_id`.

**Comment by nlincke** [comment]
Hey,

sorry for the late response. I am on vacation and the internet is not that greate out here...
Anyway, i went for the manualy way...
I did:
```
1 STATUS INBOX/Rezepte (X-GUID)
* STATUS INBOX/Rezepte (X-GUID **0d432d37602e305ac15b00007dd2b51e**)
```

and  the TERM part of the out file is
```
{
                    "term": {
                        "box": "0d432d37602e305ac15b00007dd2b51e"
                    }
                }
```

So I guess the mail server is working as intended and so does your plugin!
It keeps me questioning why the gmail app is acting the way it does. Obviously it does not search inside a directory if i selected one...

I keep investigating my problem on the client side. Until then, is there a way to not search for the box GUID? I understand that this is not the way IMAP should work...

Most clients which I use do search locally. I want to have fast server side search for espacally for mobile clients like the gmail app...

Best thing I could ask for is a config switch or something...
... is there an easy way or do I need to patch the source code if i want to have this?

**Comment by nlincke** [comment]
Seams that i am not the only one with this problem: https://support.google.com/mail/thread/11287729?hl=en

**Comment by filiphanes** [comment]
If I omit box field from elastic query it will return duplicate UIDs and if client is expecting UIDs from INBOX, following FETCH on SELECTed INBOX will try to fetch non-existing and/or wrong messages.

You could check what exact commands is gmail client sending to IMAP by enablig rawlog_dir in imap protocol config https://wiki.dovecot.org/Debugging/Rawlog. From your information I expect it will be simply SEARCHing in INBOX.

Second idea is what if gmail client is expecting \All mailbox and fallbacks to INBOX. Gmail IMAP has \All mailbox named "[Gmail]/All Mail"
You could try to setup mailbox named virtual/All or "[Gmail]/All Mail"
 with special-use flag \All https://doc.dovecot.org/configuration_manual/virtual_plugin/ so that client can see it in LIST command.

Then there is question how this client would match message from \All to original mailbox to avoid refetching already FETCHed data.
In original Gmail IMAP there are X-GM-MSGID and X-GM-LABELS containing user folders. (using capability X-GM-EXT-1) 
https://developers.google.com/gmail/imap/imap-extensions
In Dovecot there are X-GUID and X-MAILBOX (no capability).
You could try to manually put X-GM-EXT-1 to dovecot capabilities to see if gmail client will try to use them.
There is possibility to create a dovecot plugin which exposes X-GUID and X-MAILBOX as X-GM-MSGID and X-GM-LABELS if this would help for gmail client.

You can search or ask in dovecot mailing list, there are many guys who are more experienced than me.
